name: Build and test GeCo i2b2 data source
# todo: i2b2 push when? is build fast enough?
on:
  push:
  workflow_dispatch:
jobs:
  ci-cd:
    name: Build and test GeCo i2b2 data source
    runs-on: ubuntu-latest
#    env:
#      PUSH: ${{ github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags') }} todo: also put if manual trigger

    steps:
      - name: Setup SSH deploy key for private repositories
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: |
            ${{ secrets.GECO_SSH_DEPLOY_KEY }}
            ${{ secrets.SPINDLE_SSH_DEPLOY_KEY }}

      - name: TEST cloning geco
        run: git clone git@github.com:ldsec/geco.git

      - name: TEST cloning spindle
        run: git clone git@github.com:ldsec/spindle.git

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.LDS_PKG_PAT }}
          submodules: true

      - name: Environment
        run: |
          go version
          ./scripts/version.sh
          pushd third_party/geco && ./scripts/version.sh && popd
          env

      - name: Setup Git and Golang environment for private repositories
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          go env -w GOPRIVATE=github.com/ldsec/geco,github.com/ldsec/spindle,github.com/ldsec/geco-i2b2-data-source

      - name: Generate GeCo Swagger files
        run: make geco-swagger-gen

      - name: Go sources beautification
        run: make go-imports go-lint

      - name: Build data source plugin
        run: make go-build-plugin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Get versions
        id: get_versions
        run: |
          DATASOURCE_VERSION=$(scripts/version.sh)
          echo ::set-output name=datasource_version::${DATASOURCE_VERSION}
          echo ::set-output name=i2b2_docker_image::ghcr.io/ldsec/i2b2-geco:${DATASOURCE_VERSION}

      - name: Build i2b2 Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./build/package/i2b2
          build-args: BUILD=docker
          load: true
          ssh: default
          tags: ${{ steps.get_version.outputs.i2b2_docker_image }}
          cache-from: type=gha,scope=buildkit
          cache-to: type=gha,scope=buildkit,mode=max

      - name: Start deployments
        run: |
          make geco-docker-compose ARGS="up -d postgresql"
          make i2b2-docker-compose ARGS="up -d"

      - name: Run i2b2 docker image test
        run: |
          sudo apt-get install -y libxml2-utils
          make i2b2-test

      - name: Run go unit tests
        run: make go-unit-tests

      - name: Show GeCo deployment logs
        if: always()
        run: make geco-docker-compose ARGS="logs"

      - name: Show i2b2 deployment logs
        if: always()
        run: make i2b2-docker-compose ARGS="logs"

#      - name: Login to GitHub Container Registry
#        if: ${{ env.PUSH }}
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.LDS_PKG_PAT_USERNAME }}
#          password: ${{ secrets.LDS_PKG_PAT }}

#      - name: Push GeCo Docker image
#        if: ${{ env.PUSH }}
#        run: docker push ${{ steps.get_version.outputs.i2b2_docker_image }}
