name: Build i2b2 docker image and run some tests
on:
  push: #todo: determine when to trigger
  workflow_dispatch:
jobs:
  i2b2:
    name: i2b2 docker image build and test
    runs-on: ubuntu-latest
#    env:
#      PUSH: ${{ github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags') }}

    steps:
      - name: Environment
        run: |
          go version
          env

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

#      - name: Setup SSH deploy key for private repositories
#        uses: webfactory/ssh-agent@v0.4.1
#        with:
#          ssh-private-key: ${{ secrets.GECO_SSH_DEPLOY_KEY }}

#      - name: Setup Git and Golang environment for private repositories
#        run: |
#          git config --global url."git@github.com:".insteadOf "https://github.com/"
#          go env -w GOPRIVATE=github.com/ldsec/geco,github.com/ldsec/spindle,github.com/ldsec/geco-i2b2-data-source

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Get versions
#        id: get_versions
#        run: |
#          VERSION=$(scripts/version.sh)
#          GECO_VERSION=$(cd test/geco && scripts/version.sh)
#          echo ::set-output name=version::${VERSION}
#          echo ::set-output name=geco_version::${GECO_VERSION}
#          echo ::set-output name=i2b2_docker_tag::ghcr.io/ldsec/i2b2-geco:${VERSION}

#          # todo: GET VERSION OF i2b2 SOMEWHERE AND SET THIS AS VERSION ON DOCKER
#          use a variant of PUSH? or have it only manual? in terms of being triggered

      - name: Build i2b2 Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./build/package/i2b2
          build-args: BUILD=docker
          load: true
          ssh: default
          # tags: ${{ steps.get_version.outputs.docker_tag }}
          tags: ghcr.io/ldsec/i2b2-geco
          cache-from: type=gha,scope=buildkit
          cache-to: type=gha,scope=buildkit,mode=max

      - name: Start GeCo deployment
        run: |
          make start-geco-dev-local-3nodes
          sleep 10  # todo

      - name: Start i2b2
        run: |
          make i2b2-docker-compose ARGS="up -d"
          sleep 10  # todo

      - name: Run i2b2 test
        run: make test-i2b2

      - name: Show deployment logs
        if: always()
        run: make -C third_party/geco/deployments/dev-local-3nodes docker-compose ARGS="logs"

#      - name: Login to GitHub Container Registry
#        if: ${{ env.PUSH }}
#        uses: docker/login-action@v1
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.LDS_PKG_PAT_USERNAME }}
#          password: ${{ secrets.LDS_PKG_PAT }}

#      - name: Push GeCo Docker image
#        if: ${{ env.PUSH }}
#        run: docker push ${{ steps.get_version.outputs.i2b2_docker_tag }}
